#config.ini file directory
config_directory: "C:/Users/David/Desktop/Git/PETsyScan/test_data/FEM128/"

#PETsys binaries directory 
petsys_directory: "C:/Users/David/Desktop/Git/PETsys_sw_fake/"

#output base name and directory
out_name: "20240131_debug"
out_directory: "C:/Users/David/Desktop/Git/PETsyScan/test_data/"

#FEM being used (FEM128/FEM256)
FEM: "FEM128"

#FEB/D being used (FEBD1k/FEBD8k)
FEBD: "FEBD1k"

#BIAS board mezzanine (BIAS_16P, BIAS_32P, BIAS_64P)
BIAS_board: "BIAS_16P"

# Indicate reference detector:
# 1- FEB/D portID if there is, -1 if no reference detector is present (always starting from 0)
# 2- Voltages [Vpre-break, Vbreak, Vov]
# 3- Thresholds
ref_det_febd: 2
ref_det_volt: [30.0, 37.5, 3.0]
ref_det_ths: [30, 15, 12]

# bias_map.csv location
bias_file: "test_data/bias_map_corrected.csv"

#acquisition mode (qdc,tot)
mode: "qdc"

#HW trigger (True/False)
hw_trigger: False

#acquistion time
time: 31.1

#data process (coincidence/singles/group), (binary, txt, root), Compact (True/False)
data_type: coincidence
data_format: binary
data_compact: True
fraction: 100
hits: 64

#offset voltage
prebreak_voltage: 40.0

#Vbreak
break_voltage: 50.0

#over-voltage list
over_voltage: [4.2]

#T1 threshold list
vth_t1: [15]

#T2 threshold list
vth_t2: [17]

#E threshold list
vth_e: [1]

# Number of iterations of the whole scan
iterations: 1

# Time between iterations in seconds
time_between_iterations: 10.0

# MOTOR PARAMETERS IF USED FOR SCAN
# -------------------------------

# Motor flag (True/False)
motor: True

# Number of motors (1, 2 or 3)
num_motors: 1

# Motor name and parameters. If motor is False, these parameters are ignored
# start and end are in mm
# step_size is in mm
# microstep is the microstep of the motor driver (1, 2, 4, 8, 16, 32)
# relation is the relation between the motor and the detector (mm/rev)
# speed is the speed of the motor (steps/s)
# max_speed is the maximum speed of the motor (steps/s)
# acceleration is the acceleration of the motor (steps/s^2)

# Initial position number to continue with the scan if it was stopped (use pos_ini = 0 to start from the beginning)
pos_ini: 0

motorX:
  type: linear      # Can be linear or rotatory
  start: 10.0       # Initial position in mm or degrees
  end: 14.5         # Final position in mm or degrees
  step_size: 0.8    # Step size in mm or degrees
  microstep: 16     # Microstep of the motor driver
  relation: 1.5     # Relation between the motor and the detector (only used in the linear, mm/rev)
  speed: 4000       # Speed of the motor (steps/s)
  max_speed: 4000   # Maximum speed of the motor (steps/s)
  acceleration: 800 # Acceleration of the motor (steps/s^2)
  
motorY:
  type: linear
  start: 2.0
  end: 10.0
  step_size: 0.2
  microstep: 1
  relation: 0.5
  speed: 200
  max_speed: 200
  acceleration: 50

motorZ:
  type: linear
  start: 2.0
  end: 10.0
  step_size: 0.2
  microstep: 1
  relation: 0.5
  speed: 200
  max_speed: 200
  acceleration: 50




